<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="page-header">
    <h1>
        Typy Čepadiel
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["pump_types/new", "Nový typ"]) ?>
    </p>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Name</th>
            <th>Manufacturer</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $pump_type): ?>
            <tr>
                <td><?php echo $pump_type->getId() ?></td>
            <td><?php echo $pump_type->getName() ?></td>
            <td><?php echo $pump_type->getManufacturer() ?></td>

                <td><?php echo $this->tag->linkTo(["pump_types/edit/" . $pump_type->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["pump_types/delete/" . $pump_type->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("pump_types/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("pump_types/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("pump_types/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("pump_types/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
