<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Vizualizácia</h3>
    </div>
	<?php echo $this->flashSession->output(); ?>
    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right">
        <div class="input-group">
<!--          <span class="input-group-btn">
            <a href="/device_controller/devsetup/addDevice/" class="btn btn-success" ><i class="fa fa-plus"></i> Nové zariadenie</a>
          </span>-->
        </div>
      </div>
    </div>
  </div>

  <div class="clearfix"></div>
  
<div class="row">
    <!-- Start to do list -->
    <div class="col-md-12 col-sm-12 col-xs-12">
		<div class="" role="tabpanel" data-example-id="togglable-tabs">
			<ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
				<?php
				foreach($devices as $device){
					echo "<li role=\"presentation\" class=\"".(($active == $device->id)?"active":"")."\">";
						echo "<a href=\"/device_controller/graphs/index/".$device->id."\" role=\"tab\">".$device->name."</a>";
					echo "</li>";
				}
				
				?>
				
<!--			  <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Home</a>
			  </li>
			  <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Profile</a>
			  </li>
			  <li role="presentation" class=""><a href="#tab_content3" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="false">Profile</a>
			  </li>-->
			</ul>
<!--			<div id="myTabContent" class="tab-content">
			  <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
				<p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
				  synth. Cosby sweater eu banh mi, qui irure terr.</p>
			  </div>
			  <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
				<p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo
				  booth letterpress, commodo enim craft beer mlkshk aliquip</p>
			  </div>
			  <div role="tabpanel" class="tab-pane fade" id="tab_content3" aria-labelledby="profile-tab">
				<p>xxFood truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo
				  booth letterpress, commodo enim craft beer mlkshk </p>
			  </div>
			</div>-->

			<?php
//				foreach ($points as $point){
//					echo $point["time"]."<br>";
//				}
			?>
			<button id="testButton"> Fetch data</button>
			<button id="testGraph">Test graph</button>
			<div id="text"></div>
<!--			<div id="graph"></div>-->

			<p>AC MODULY</p>
			<div class="ac_graphs">
			<?php 
			//AC module graphs
			$lol = 0;
			if(!empty($ac_modules)){
				foreach ($ac_modules as $ac_module){
//					if($lol < 2){
					echo "<div class=\"row\">";
					echo "<div class =\"ac_state\" id=\"state_".$ac_module->on_device_id."\" module=\"".$ac_module->on_device_id."\"></div>";
					echo "<div class =\"ac_cur\" id=\"cur_".$ac_module->on_device_id."\" module=\"".$ac_module->on_device_id."\"></div>";
					echo "</div>";
//					$lol++;
//					}
				}
				echo "<div id=\"ac_temp\"></div>";
			}
			?>
			</div>
<!--			<div class="row">
			PH
			<iframe src="http://147.175.116.116:3000/dashboard-solo/db/test_1?refresh=5s&panelId=5&orgId=1&from=1523743200000&to=1524054677272&theme=light" width="450" height="200" frameborder="0"></iframe>
			ORP
			<iframe src="http://147.175.116.116:3000/dashboard-solo/db/test_1?refresh=5s&panelId=6&orgId=1&from=1523743200000&to=1524055173897&theme=light" width="450" height="200" frameborder="0"></iframe>
			vodivost
			<iframe src="http://147.175.116.116:3000/dashboard-solo/db/test_1?refresh=5s&panelId=7&orgId=1&from=1523743200000&to=1524054922761&theme=light" width="450" height="200" frameborder="0"></iframe>
			tds
			<iframe src="http://147.175.116.116:3000/dashboard-solo/db/test_1?refresh=5s&panelId=8&orgId=1&from=1523743200000&to=1524055447085&theme=light" width="450" height="200" frameborder="0"></iframe>
			O2
			<iframe src="http://147.175.116.116:3000/dashboard-solo/db/test_1?refresh=5s&panelId=9&orgId=1&from=1523743200000&to=1524055503922&theme=light" width="450" height="200" frameborder="0"></iframe>
			O2 saturacia
			<iframe src="http://147.175.116.116:3000/dashboard-solo/db/test_1?refresh=5s&panelId=10&orgId=1&from=1523743200000&to=1524055618742&theme=light" width="450" height="200" frameborder="0"></iframe>
			teplota
			<iframe src="http://147.175.116.116:3000/dashboard-solo/db/test_1?refresh=5s&panelId=11&orgId=1&from=1523743200000&to=1524055689469&theme=light" width="450" height="200" frameborder="0"></iframe>
			</div>
			bdd
			<div class="row">
			<iframe src="http://147.175.116.116:3000/dashboard-solo/db/test_1?refresh=5s&panelId=12&orgId=1&from=1523743200000&to=1524057285983&theme=light" width="450" height="200" frameborder="0"></iframe>
			<iframe src="http://147.175.116.116:3000/dashboard-solo/db/test_1?refresh=5s&panelId=13&orgId=1&from=1523743200000&to=1524057847903&theme=light" width="450" height="200" frameborder="0"></iframe>
			<iframe src="http://147.175.116.116:3000/dashboard-solo/db/test_1?refresh=5s&panelId=14&orgId=1&from=1523743200000&to=1524057882942&theme=light" width="450" height="200" frameborder="0"></iframe>
			</div>
			<div class="row">
				<iframe src="http://147.175.116.116:3000/dashboard-solo/db/test_1?refresh=5s&panelId=16&orgId=1&from=1523743200000&to=1524061294303&theme=light" width="450" height="200" frameborder="0"></iframe>
				<iframe src="http://147.175.116.116:3000/dashboard-solo/db/test_1?refresh=5s&panelId=15&orgId=1&from=1523743200000&to=1524061133308&theme=light" width="450" height="200" frameborder="0"></iframe>
				<iframe src="http://147.175.116.116:3000/dashboard-solo/db/test_1?refresh=5s&panelId=4&orgId=1&from=1523743200000&to=1524054508074&theme=light" width="450" height="200" frameborder="0"></iframe>
			</div>
			<a href="http://147.175.116.116:3000/dashboard/db/test_1?refresh=5s&orgId=1&panelId=4&fullscreen&from=1514764800000&to=1517443199000">dashboard</a>-->
		  </div>
    </div>
    <!-- End to do list -->    
</div>
</div>
