<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["modules", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create modules
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "modules/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldOnDeviceId" class="col-sm-2 control-label">On Of Device</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["on_device_id", "type" => "number", "class" => "form-control", "id" => "fieldOnDeviceId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdDevice" class="col-sm-2 control-label">Id Of Device</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_device", "type" => "number", "class" => "form-control", "id" => "fieldIdDevice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAddress" class="col-sm-2 control-label">Address</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["address", "size" => 30, "class" => "form-control", "id" => "fieldAddress"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdModuleType" class="col-sm-2 control-label">Id Of Module Of Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_module_type", "type" => "number", "class" => "form-control", "id" => "fieldIdModuleType"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
