<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="page-header">
    <h1>
        Typy Modulov
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["modules/new", "Nový modul"]) ?>
    </p>
</div>


<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>On Of Device</th>
            <th>Id Of Device</th>
            <th>Address</th>
            <th>Name</th>
            <th>Id Of Module Of Type</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $module): ?>
            <tr>
                <td><?php echo $module->getOnDeviceId() ?></td>
            <td><?php echo $module->getIdDevice() ?></td>
            <td><?php echo $module->getAddress() ?></td>
            <td><?php echo $module->getName() ?></td>
            <td><?php echo $module->getIdModuleType() ?></td>

                <td><?php echo $this->tag->linkTo(["modules/edit/" . $module->getOnDeviceId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["modules/delete/" . $module->getOnDeviceId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("modules/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("modules/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("modules/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("modules/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
