<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="page-header">
    <h1>
        Typy modulov
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["module_types/new/new", "Nový modul"]) ?>
    </p>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Name</th>
            <th>No Of Submodules</th>
            <th>Color</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $module_type): ?>
            <tr>
                <td><?php echo $module_type->getId() ?></td>
            <td><?php echo $module_type->getName() ?></td>
            <td><?php echo $module_type->getNoSubmodules() ?></td>
            <td><?php echo $module_type->getColor() ?></td>

                <td><?php echo $this->tag->linkTo(["module_types/edit/" . $module_type->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["module_types/delete/" . $module_type->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("module_types/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("module_types/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("module_types/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("module_types/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
