<div class="">
  <div class="page-title">
    <div class="title_left">
      <h3>Zariadenia</h3>
    </div>
	<?php echo $this->flashSession->output(); ?>
    <div class="title_right">
      <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right">
        <div class="input-group">
          <span class="input-group-btn">
            <a href="/device_controller/devsetup/addDevice/" class="btn btn-success" ><i class="fa fa-plus"></i> Nové zariadenie</a>
          </span>
        </div>
      </div>
    </div>
  </div>

  <div class="clearfix"></div>
  
<div class="row">
    <!-- Start to do list -->
    <div class="col-md-12 col-sm-12 col-xs-12">
		
    </div>
    <!-- End to do list -->    
</div>
</div>
