<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["pumps", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create pumps
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "pumps/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdPumpType" class="col-sm-2 control-label">Id Of Pump Of Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_pump_type", "type" => "number", "class" => "form-control", "id" => "fieldIdPumpType"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdDevice" class="col-sm-2 control-label">Id Of Device</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_device", "type" => "number", "class" => "form-control", "id" => "fieldIdDevice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAddress" class="col-sm-2 control-label">Address</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["address", "size" => 30, "class" => "form-control", "id" => "fieldAddress"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdPumpSubgroup" class="col-sm-2 control-label">Id Of Pump Of Subgroup</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_pump_subgroup", "type" => "number", "class" => "form-control", "id" => "fieldIdPumpSubgroup"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
