<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="page-header">
    <h1>
        Čerpadlá
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["pumps/new", "Nové čerpadlo"]) ?>
    </p>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Id Of Pump Of Type</th>
            <th>Id Of Device</th>
            <th>Address</th>
            <th>Id Of Pump Of Subgroup</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $pump): ?>
            <tr>
                <td><?php echo $pump->getId() ?></td>
            <td><?php echo $pump->getIdPumpType() ?></td>
            <td><?php echo $pump->getIdDevice() ?></td>
            <td><?php echo $pump->getAddress() ?></td>
            <td><?php echo $pump->getIdPumpSubgroup() ?></td>

                <td><?php echo $this->tag->linkTo(["pumps/edit/" . $pump->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["pumps/delete/" . $pump->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("pumps/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("pumps/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("pumps/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("pumps/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
